//
//  AccessoryUIKit.swift
//  ProjectName
//
//  Created by Happens, Inc.  on 9/26/15.
//  Copyright (c) 2015 Happens. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class AccessoryUIKit : NSObject {

    

}

